### ISSUE TITLE
Cannot import name 'AirFreshA1' from 'miio' 

### ISSUE THREAD

**Issue by jbustdel** [syssi/xiaomi_airpurifier#167]
Since update HA to 2021.4.3 and xiaomi_airpurifier 0.6.5 appears the error:

_Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirFreshA1' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)_

Configuration.yaml

fan:
  - platform: xiaomi_miio_airpurifier
    name: Xiaomi Air Purifier 3 H
    host: 192.168.0.152
    token: xxx
    model: zhimi.airpurifier.mb3

Versión | core-2021.4.3
-- | --
Tipo de instalación | Home Assistant OS
Desarrollo | false
Supervisor | true
Docker | true
Entorno virtual | false
Versión de Python | 3.8.7
Nombre del Sistema Operativo | Linux
Versión del Sistema Operativo | 5.4.109
Arquitectura de CPU | x86_64
Zona horaria | Europe/Madrid

{
  "domain": "xiaomi_miio_airpurifier",
  "name": "Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration",
  "version": "0.6.5",
  "config_flow": false,
  "documentation": "https://github.com/syssi/xiaomi_airpurifier",
  "issue_tracker": "https://github.com/syssi/xiaomi_airpurifier/issues",
  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.5"
  ],
  "dependencies": [],
  "codeowners": [
    "@syssi"
  ]
}

The solution here https://github.com/syssi/xiaomi_airpurifier/issues/98 dont solve the problem.

**Comment by pervolianinen** [comment]
same error HA 2021.3.4.
After uptdate aomi_airpurifier 0.6.4 to 0.6.5 "_...cannot import name 'AirFreshA1' from 'miio'..._"
On 0.6.4 work fine

**Comment by syssi** [comment]
This happens if the `python-miio` version isn't the required version (`>=0.5.5`). Do you additional `custom_components` with manifests mentioning/requiring `python-miio` as dependency? Please make sure python-miio 0.5.5 is in use.

**Comment by jbustdel** [comment]
Ok. Solved. The problem was the miio plug component. Update manifest.json 0.5.4 to 5.5.5, reboot and its ok now. 

Thanks.
