### ISSUE TITLE
Cannot import name 'AirHumidifierMiot' from 'miio'" - workaround

### ISSUE THREAD

**Issue by Morph26** [syssi/xiaomi_airpurifier#98]
Get error, when check config:
`Platform error fan.xiaomi_miio_airpurifier - cannot import name 'AirHumidifierMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)`

Error appears, when adding to configuration.yaml:
```
fan:
  - platform: xiaomi_miio_airpurifier
    name: mi_humidifier_child
    host: 192.168.x.xx
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    model: deerma.humidifier.mjjsq
```
                        
HA supervised. Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration installed via HACS.
System info:
```
arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.15
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.72
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Moscow
version | 0.117.4
virtualenv | false

```

**Comment by syssi** [comment]
Which version did you install via HACS?

**Comment by Morph26** [comment]
> 
> 
> Which version did you install via HACS?

```
{
  "domain": "xiaomi_miio_airpurifier",
  "name": "Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration",
  "config_flow": false,
  "documentation": "https://github.com/syssi/xiaomi_airpurifier",
  "issue_tracker": "https://github.com/syssi/xiaomi_airpurifier/issues",
  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.3"
  ],
  "dependencies": [],
  "codeowners": [
    "@syssi"
  ]
}
```

**Comment by syssi** [comment]
The manifest.json doesn't contain the git tag. Which version of the custom component did you select at the version dropdown at HACS?

**Comment by Morph26** [comment]
Installed from HACS (Search and Install button) and version 0.6.1

**Comment by iwzoo** [comment]
same error here
it works if I change the lines to:
```
from miio.airhumidifier_miot import AirHumidifierMiot
from miio import (  # pylint: disable=import-error
    AirFresh,
    AirHumidifier,
    AirHumidifierJsq,
    # AirHumidifierMiot,
    AirHumidifierMjjsq,
    AirPurifier,
    AirPurifierMiot,
    Device,
    DeviceException,
    Fan,
    FanP5,
)

```

**Comment by syssi** [comment]
The strange thing is: This custom component requires python-miio 0.5.3. This version provides the AirPurifierMiot class. This is the proof:

```
$ pip3 install python-miio==0.5.3 -U
Collecting python-miio==0.5.3
  Using cached https://files.pythonhosted.org/packages/0c/68/dda208e029165947f4cbc6db08c10ae4359ce68c6bb34af005320ccd5aa1/python_miio-0.5.3-py3-none-any.whl
[...]
Installing collected packages: cryptography, python-miio
  Found existing installation: cryptography 3.2.1
    Uninstalling cryptography-3.2.1:
      Successfully uninstalled cryptography-3.2.1
  Found existing installation: python-miio 0.5.4
    Uninstalling python-miio-0.5.4:
      Successfully uninstalled python-miio-0.5.4
  The scripts miceil, mieye, miio-extract-tokens, miiocli, miplug and mirobo are installed in '/home/sebastian/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cryptography-2.9.2 python-miio-0.5.3

$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from miio import AirHumidifierMiot
>>> 
```

The `cannot import name 'AirHumidifierMiot' from 'miio'` error shouldn't happen if python-miio 0.5.3 is installed. Why isn't this requirement fulfilled on your installation?

**Comment by fufar** [comment]
I have another error with this model. Errors starts with last version, before works fine

`Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)`

I use homeassistant/qemux86-64-homeassistant:0.117.5 container, it has 0.5.4 python-miio
```
ash-4.3# docker exec -it 64114 bash
bash-5.0# pip3 list | grep miio
python-miio                      0.5.4
```

```
bash-5.0# python3
Python 3.8.6 (default, Oct 14 2020, 15:45:05)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from miio import AirHumidifierMiot
>>> from miio import FanMiot
>>>
```

**Comment by syssi** [comment]
@fufar Can we try to make sure you don't have multiple python-miio versions installed in different paths? Plase check the file

```
/usr/local/lib/python3.8/site-packages/miio/__init__.py
```

Do you see a `FanMiot` line here? I assume not. In this case it's not 0.5.4.

**Comment by fufar** [comment]
> @fufar Can we try to make sure you don't have multiple python-miio versions installed in different paths? Plase check the file
> 
> ```
> /usr/local/lib/python3.8/site-packages/miio/__init__.py
> ```
> 
> Do you see a `FanMiot` line here? I assume not. In this case it's not 0.5.4.

```
bash-5.0# cat /usr/local/lib/python3.8/site-packages/miio/__init__.py | grep FanMiot
from miio.fan_miot import FanMiot, FanP9, FanP10, FanP11
```

**Comment by fufar** [comment]
Reinstall via HACS to 0.6.0 - works ok for me

**Comment by syssi** [comment]
@rytilahti Do you have an idea what's going on here? I don't get it. ;-)

**Comment by rytilahti** [comment]
Hmm, maybe a problem with circular dependencies that sometimes works due to different import order / being cached by another integration? Maybe conflicting versions, in case multiple custom components are active?

Or considering that reinstallation helps, maybe some old remnants from previous version was still in place? Other than those, I cannot think anything at the moment :-)

Btw, you can easily check which version is in use by accessing the version, it may be worth adding a debug output for initialization to make it easy to check which version was in use when the log was created?
```
bpython version 0.19 on top of Python 3.8.6 /home/hass/venv/bin/python
>>> import miio
>>> miio.__version__
'0.5.3'
>>> 
```

**Comment by syssi** [comment]
I hit the same issue today:

```
2020-11-18 15:15:20 ERROR (MainThread) [homeassistant.config] Platform error: fan
Traceback (most recent call last):
  File "/srv/homeassistant-sebastian/lib/python3.7/site-packages/homeassistant/config.py", line 823, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/srv/homeassistant-sebastian/lib/python3.7/site-packages/homeassistant/loader.py", line 422, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant-sebastian/lib/python3.7/site-packages/homeassistant/loader.py", line 427, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/homeassistant-sebastian/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 7, in <module>
    from miio import (  # pylint: disable=import-error
```

If I check the age of the `__init__.py` we can see the pip package is installed on every reboot:

```
$ ls -l lib/python3.7/site-packages/miio/__init__.py         
-rw-r--r-- 1 homeassistant homeassistant 2483 Nov 18 15:15 lib/python3.7/site-packages/miio/__init__.py
```

As soon as HA and the custom component uses the same python-miio version the issue will be gone.

**Comment by slydiman** [comment]
I got the error 
`Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' `
today with HA 0.118.0 after upgrading xiaomi_airpurifier from 0.6.1 to 0.6.2
I tried HACS and manual install from downloaded xiaomi_airpurifier-develop.zip
Downgraded back to 0.6.1

**Comment by evgeniikim** [comment]
Error: Platform error fan.xiaomi_miio_airpurifier - cannot import name 'FanMiot' from 'miio' (/usr/local/lib/python3.8/site-packages/miio/__init__.py)
device: Smartmi Humidifier Evaporator 2 | zhimi.humidifier.ca4 | CJXJSQ04ZM
HS: 0.118.0
xiaomi_airpurifier: 0.6.2

but on 0.6.1 - it's ok.

**Comment by Velly56** [comment]
Error: Invalid config for [fan.xiaomi_miio_airpurifier]: value is not allowed for dictionary value @ data['model']. Got 'deerma.humidifier.jsq'. (See ?, line ?).
device:  deerma.humidifier.jsq
HA: 0.118.1
xiaomi_airpurifier: 0.6.2

**Comment by anschein** [comment]
same problem with HA 0.117.6,and xiaomi_airpurifier: 0.6.2
rollback to 0.6.1 works fine

**Comment by dreem2001** [comment]
The same thing on 118 HA. Rolled back to 0.6.1

**Comment by syssi** [comment]
I found a workaround which works for me. Copy the official `xiaomi_miio` component to your `custom_components` folder and edit the `manifest.json`. The updated dependencies must be used here:

```
{
  "domain": "xiaomi_miio",
  "name": "Xiaomi Miio",
  "config_flow": true,
  "documentation": "https://www.home-assistant.io/integrations/xiaomi_miio",
  "requirements": ["construct==2.10.56", "python-miio==0.5.4"],
  "codeowners": ["@rytilahti", "@syssi", "@starkillerOG"],
  "zeroconf": ["_miio._udp.local."]
}
```

Reboot HA. This solves the issue of different required `python-miio` and `construct` versions. All manifest.json's of python-miio dependend custom components requires the same version/line at the manifest:

````
  "requirements": ["construct==2.10.56", "python-miio==0.5.4"],
```

If this is fulfilled the errors are gone. As soon HA 0.119 is reased the `xiaomi_miio` folder can be removed again.

**Comment by syssi** [comment]
A new HA version was released yesterday. Please update your HA instance and remove `xiaomi_miio` from your `custom_components` directory. This workaround isn't required anymore.

**Comment by neo799** [comment]
Hi, I updated to the latest  Home Assistant OS 5.9 Supervisor Version 2020.12.7 but the error is still there. I Installed version 0.6.2 via HACS. Any ideas?

**Comment by syssi** [comment]
@neo799 Could you provide a list of your installed/used custom components?

**Comment by neo799** [comment]
Currently the following custom components are installed.
- hacs
- miheater
- mikrotik_router
- wechat
- xiaomi_miio_airpurifier
- xiaomi_miio_plug
- xiaomi_miio_raw
I also uninstalled all the miio before and tried to use my air purifiers with the standard component but it does not work anymore.

**Comment by syssi** [comment]
I'm asking about the custom component because I assume there is an custom component with an outdated python-miio requirement. Could you provide the content of all `manifest.json` files at your custom components folder?

```
# example

$ find custom_components -name manifest.json
custom_components/xiaomi_miio_airpurifier/manifest.json
custom_components/xiaomi_cloud_map_extractor/manifest.json
custom_components/nextbike/manifest.json
custom_components/scheduler/manifest.json
custom_components/xiaomi_miio_philipslight/manifest.json
custom_components/hacs/manifest.json
custom_components/xiaomi_miio_cooker/manifest.json
$
$ find custom_components -name manifest.json -exec cat "{}" \;
{
  "domain": "xiaomi_miio_airpurifier",
  "name": "Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration",
  "config_flow": false,
  "documentation": "https://github.com/syssi/xiaomi_airpurifier",
  "issue_tracker": "https://github.com/syssi/xiaomi_airpurifier/issues",
  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.4"
  ],
  "dependencies": [],
  "codeowners": [
    "@syssi"
  ]
}
{
  "domain": "xiaomi_cloud_map_extractor",
  "name": "Xiaomi Cloud Map Extractor",
[...]
```

**Comment by neo799** [comment]
Looks like the Mi Heater could be the issue then.

{
  "domain": "miheater",
  "name": "Smartmi Smart Heater",
  "documentation": "https://github.com/fineemb/Smartmi-smart-heater",
  "requirements": [
    "construct==2.9.45",
    "python-miio==0.5.0.1"
  ],
  "dependencies": [],
  "codeowners": [
    "@fineemb"
  ]
}
------------------------------------------------------

{
  "domain": "xiaomi_miio_airpurifier",
  "name": "Xiaomi Mi Air Purifier, Air Humidifier, Air Fresh and Pedestal Fan Integration",
  "config_flow": false,
  "documentation": "https://github.com/syssi/xiaomi_airpurifier",
  "issue_tracker": "https://github.com/syssi/xiaomi_airpurifier/issues",
  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.4"
  ],
  "dependencies": [],
  "codeowners": [
    "@syssi"
  ]
}
-----------------------------------------------------

{
  "domain": "xiaomi_miio_plug",
  "name": "Xiaomi Mi Smart WiFi Socket",
  "config_flow": false,
  "documentation": "https://github.com/syssi/xiaomiplug",
  "issue_tracker": "https://github.com/syssi/xiaomiplug/issues",
  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.3"
  ],
  "dependencies": [],
  "codeowners": [
    "@syssi"
  ]
}
-------------------------------------------------

{
  "domain": "xiaomi_miio_raw",
  "name": "Custom component for Home Assistant to faciliate the reverse engeneering of Xiaomi MiIO devices",
  "config_flow": false,
  "documentation": "https://github.com/syssi/xiaomi_raw",
  "issue_tracker": "https://github.com/syssi/xiaomi_raw/issues",
  "requirements": [
    "construct==2.10.56",
    "python-miio>=0.5.3"
  ],
  "dependencies": [],
  "codeowners": [
    "@syssi"
  ]
}

**Comment by neo799** [comment]
Thanks buddy. That was the issue. I deleted all other xiaomi custom components and now it works. Now i just need to find a fix for my heater. Thanks and Happy new year to you.

**Comment by syssi** [comment]
@neo799 just update the manifest.json of the heater to:

```
"construct==2.10.56",
"python-miio>=0.5.4"
```

**Comment by neo799** [comment]
@syssi That's what I did ;-) Guten Rutsch ins neue Jahr. Greetings from Shanghai
